<?php echo $this->doctype() ?>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Zend Quick Start</title>
    <link href="http://current.bootstrapcdn.com/bootstrap-v204/css/bootstrap-combined.min.css" rel="stylesheet" type="text/css" />
    <?php echo $this->headLink()->appendStylesheet('/main.css') ?>
    
    <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.7.2.min.js " type="text/javascript"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js" type="text/javascript"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.dataTables/1.9.1/jquery.dataTables.js" type="text/javascript"></script>
    <script src="http://current.bootstrapcdn.com/bootstrap-v204/js/bootstrap.min.js" type="text/javascript"></script>
</head>

<body data-spy="scroll" data-target=".subnav" data-offset="50">
    <div class="navbar navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <a class="brand" href="#">Zend Quick Start</a>
                <div>
                    <ul class="nav">
                        <li><a href="#">Menu 1</a></li>
                        <li><a href="#">Menu 2</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
<?php echo $this->layout()->content; ?>
    </div>
    <div class="container" style="text-align:center; padding: 50px 0 20px">
        <h6>Copyright &copy; 2012. Edvantis</h6>
    </div>
</body>
</html>
